/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controllers.PedidosController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;

/**
 *
 * @author Clara Elizabeth
 */
public class ViewPedido extends javax.swing.JFrame {
    
     private final PedidosController controller;
     private ArrayList<Object[]> clientes;
    private ArrayList<Object[]> pedidos;
    private SimpleDateFormat fecha;
    
    private DefaultTableModel model;
    
    /**
     * Creates new form ViewPedido
     */
    public ViewPedido() {
        initComponents();
        fecha = new SimpleDateFormat("YYYY-MM-dd");
        controller = new PedidosController();
        model = (DefaultTableModel) JTblPedido.getModel();
        clientes = controller.searchCliente(-1);
        pedidos = controller.searchPedido(-1);
        updateClientes();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTxtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTxtTotal = new javax.swing.JTextField();
        JBtnGuardar = new javax.swing.JButton();
        JBtnEditar = new javax.swing.JButton();
        JBtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblPedido = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        JTxtCodigo = new javax.swing.JTextField();
        JBtnBuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        JCboCliente = new javax.swing.JComboBox<>();
        JBtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registrar Pedido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        JTxtID.setEditable(false);
        JTxtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtIDActionPerformed(evt);
            }
        });
        jPanel1.add(JTxtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 190, -1));

        jLabel4.setText("Total:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        JTxtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtTotalKeyTyped(evt);
            }
        });
        jPanel1.add(JTxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 190, -1));

        JBtnGuardar.setText("Guardar");
        JBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        JBtnEditar.setText("Editar");
        JBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        JBtnEliminar.setText("Eliminar");
        JBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        JTblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTblPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTblPedido);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 500, 540));

        jLabel5.setText("Codigo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        JTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtCodigoActionPerformed(evt);
            }
        });
        JTxtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(JTxtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 200, -1));

        JBtnBuscar.setText("Buscar");
        JBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jLabel6.setText("Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jPanel1.add(JCboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 190, -1));

        JBtnVolver.setText("Volver");
        JBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGuardarActionPerformed
        // TODO add your handling code here:
        
        if( JTxtTotal.getText().isEmpty()  || JCboCliente.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        
        
        int total = Integer.parseInt(JTxtTotal.getText());
        java.util.Date fechaD = new java.util.Date();
        String fechaS = fecha.format(fechaD);
        
        
        int idCliente = Integer.parseInt(JCboCliente.getSelectedItem().toString());
        models.Pedidos pedido = new models.Pedidos(fechaS,total,idCliente);
        controller.insertPedido(pedido);
        pedidos = controller.searchPedido(-1);
        updateTable();
    }//GEN-LAST:event_JBtnGuardarActionPerformed

    private void JBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEditarActionPerformed
        // TODO add your handling code here:
        if( JTxtTotal.getText().isEmpty() || JCboCliente.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;            
        }if(JTxtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo del producto a modificar en la barra de busqueda", "Error", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        
        int id = Integer.parseInt(JTxtID.getText());
        
        int total = Integer.parseInt(JTxtTotal.getText());
        int idCliente = searchCliente(Integer.parseInt(JCboCliente.getSelectedItem().toString()));
        models.Pedidos pedido = new models.Pedidos(id,total,idCliente);
        controller.updatePedido(pedido);
        pedidos = controller.searchPedido(-1);
        updateTable();
    }//GEN-LAST:event_JBtnEditarActionPerformed

    private void JBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEliminarActionPerformed
        // TODO add your handling code here:
        if(JTxtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo del producto a eliminar en la barra de busqueda", "Error", JOptionPane.ERROR_MESSAGE);            
            return;
        }
        String code = JTxtCodigo.getText();
        controller.deletePedido(Integer.parseInt(code));
        pedidos = controller.searchPedido(-1);
        updateTable();
    }//GEN-LAST:event_JBtnEliminarActionPerformed

    private void JBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnBuscarActionPerformed
        // TODO add your handling code here:
        int code;
        if(JTxtCodigo.getText().isEmpty()){
            code = -1;
        }else{
            code = Integer.parseInt(JTxtCodigo.getText());
        }      
        pedidos = controller.searchPedido(code);
        updateTable();
    }//GEN-LAST:event_JBtnBuscarActionPerformed

    private void JBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVolverActionPerformed
        // TODO add your handling code here:
        ViewHome home = new ViewHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnVolverActionPerformed

    private void JTxtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtIDActionPerformed

    private void JTxtTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtTotalKeyTyped
        // TODO add your handling code here:
        if(evt.getSource().equals(JTxtTotal)){
            Character c = evt.getKeyChar();
            if(!Character.isDigit(c) && !c.toString().equals("")){
                evt.consume();
            }
        }
    }//GEN-LAST:event_JTxtTotalKeyTyped

    private void JTblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTblPedidoMouseClicked
        // TODO add your handling code here:
         int row = JTblPedido.getSelectedRow();
        String id = model.getValueAt(row, 0).toString();
        
        JCboCliente.setSelectedItem(model.getValueAt(row, 1).toString());
        String total = model.getValueAt(row, 3).toString();
       
        
        JTxtID.setText(id);
        
        JTxtTotal.setText(total);
        JTxtCodigo.setText(id);
        
    }//GEN-LAST:event_JTblPedidoMouseClicked

    private void JTxtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtCodigoKeyTyped
        // TODO add your handling code here:
        if (evt.getSource().equals(JTxtCodigo)) {
            Character c = evt.getKeyChar();
            if (!Character.isDigit(c) && !c.toString().equals("")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_JTxtCodigoKeyTyped

    private void JTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtCodigoActionPerformed
    
    
    
    
    private int searchCliente(int code){
        for (int i = 0; i < clientes.size(); i++) {
            if(clientes.get(i)[1].equals(code)){
                return Integer.parseInt(clientes.get(i)[0].toString());
            }
        }
        return 0;
    }
    
    private void updateTable(){
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < model.getRowCount(); j++) {
                model.removeRow(j);
            }
        }
        for (int i = 0; i < pedidos.size(); i++) {
            model.addRow(pedidos.get(i));
        }
    }
    
    private void updateClientes(){
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < JCboCliente.getItemCount(); j++) {
                JCboCliente.removeItemAt(j);
            }
        }
        for (int i = 0; i < clientes.size(); i++) {
            JCboCliente.addItem(clientes.get(i)[0].toString());
        }
        JCboCliente.setSelectedIndex(-1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnBuscar;
    private javax.swing.JButton JBtnEditar;
    private javax.swing.JButton JBtnEliminar;
    private javax.swing.JButton JBtnGuardar;
    private javax.swing.JButton JBtnVolver;
    private javax.swing.JComboBox<String> JCboCliente;
    private javax.swing.JTable JTblPedido;
    private javax.swing.JTextField JTxtCodigo;
    private javax.swing.JTextField JTxtID;
    private javax.swing.JTextField JTxtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
