/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controllers.ClientesController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Clara Elizabeth
 */
public class ViewCliente extends javax.swing.JFrame {

    private final ClientesController controller;
    private ArrayList<Object[]> clientes;

    private DefaultTableModel model;

    /**
     * Creates new form ViewCliente
     */
    public ViewCliente() {
        initComponents();

        controller = new ClientesController();
        model = (DefaultTableModel) JTblCliente.getModel();
        clientes = controller.searchClientes(-1);
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTxtCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTxtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTxtEmail = new javax.swing.JTextField();
        JBtnGuardar = new javax.swing.JButton();
        JBtnEliminar = new javax.swing.JButton();
        JBtnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTblCliente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        JTxtBuscar = new javax.swing.JTextField();
        JBtnBuscar = new javax.swing.JButton();
        JBtnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Registro cliente:");

        jLabel2.setText("ID:");

        JTxtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtClienteKeyTyped(evt);
            }
        });

        jLabel3.setText("Nombre:");

        JTxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtNombreKeyTyped(evt);
            }
        });

        jLabel4.setText("Email:");

        JTxtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtEmailActionPerformed(evt);
            }
        });
        JTxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtEmailKeyTyped(evt);
            }
        });

        JBtnGuardar.setText("Guardar");
        JBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGuardarActionPerformed(evt);
            }
        });

        JBtnEliminar.setText("Eliminar");
        JBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEliminarActionPerformed(evt);
            }
        });

        JBtnEditar.setText("Editar");
        JBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEditarActionPerformed(evt);
            }
        });

        JTblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTblClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTblCliente);

        jLabel5.setText("Codigo;");

        JTxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtBuscarKeyTyped(evt);
            }
        });

        JBtnBuscar.setText("Buscar");
        JBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnBuscarActionPerformed(evt);
            }
        });

        JBtnVolver.setText("Volver");
        JBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBtnEditar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBtnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(JBtnEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JTxtCliente)
                                    .addComponent(JTxtNombre)
                                    .addComponent(JTxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                            .addComponent(JBtnVolver))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JTxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBtnBuscar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(JTxtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(JTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(JTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBtnGuardar)
                            .addComponent(JBtnEliminar))
                        .addGap(18, 18, 18)
                        .addComponent(JBtnEditar)
                        .addGap(55, 55, 55)
                        .addComponent(JBtnVolver))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGuardarActionPerformed
        // TODO add your handling code here:

        if (JTxtNombre.getText().isEmpty() || JTxtCliente.getText().isEmpty() || JTxtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int codigo = Integer.parseInt(JTxtCliente.getText());
        String nombre = JTxtNombre.getText();
        String email = JTxtEmail.getText();
        models.Clientes cliente = new models.Clientes(codigo, nombre, email);
        controller.insertCliente(cliente);
        clientes = controller.searchClientes(-1);
        updateTable();


    }//GEN-LAST:event_JBtnGuardarActionPerformed

    private void JBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEditarActionPerformed
        // TODO add your handling code here:
        if (JTxtNombre.getText().isEmpty() || JTxtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (JTxtBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo de la categoria a eliminar en la barra de busqueda", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int id = Integer.parseInt(JTxtCliente.getText());
        String nombre = JTxtNombre.getText();
        String email = JTxtEmail.getText();
        models.Clientes cliente = new models.Clientes(id, nombre, email);
        controller.updateCliente(cliente);
        clientes = controller.searchClientes(-1);
        updateTable();
    }//GEN-LAST:event_JBtnEditarActionPerformed

    private void JBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEliminarActionPerformed
        // TODO add your handling code here:
        if (JTxtBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo de la categoria a eliminar en la barra de busqueda", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int id = Integer.parseInt(JTxtBuscar.getText());
        controller.deleteCliente(id);
        clientes = controller.searchClientes(-1);
        updateTable();
    }//GEN-LAST:event_JBtnEliminarActionPerformed

    private void JBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnBuscarActionPerformed
        // TODO add your handling code here:
        int code;
        if (JTxtBuscar.getText().isEmpty()) {
            code = -1;
        } else {
            code = Integer.parseInt(JTxtBuscar.getText());
        }
        clientes = controller.searchClientes(code);
        updateTable();
    }//GEN-LAST:event_JBtnBuscarActionPerformed

    private void JBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnVolverActionPerformed
        // TODO add your handling code here:
        ViewHome home = new ViewHome();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JBtnVolverActionPerformed

    private void JTxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtNombreKeyTyped
        // TODO add your handling code here:
        if (evt.getSource().equals(JTxtNombre)) {
            Character c = evt.getKeyChar();
            if (!Character.isLetter(c) && !c.toString().equals("")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_JTxtNombreKeyTyped

    private void JTxtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtEmailActionPerformed

    private void JTxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtEmailKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JTxtEmailKeyTyped

    private void JTxtClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtClienteKeyTyped
        // TODO add your handling code here
        if (evt.getSource().equals(JTxtCliente)) {
            Character c = evt.getKeyChar();
            if (!Character.isDigit(c) && !c.toString().equals("")) {
                evt.consume();
            }
        }
    
    }//GEN-LAST:event_JTxtClienteKeyTyped

    private void JTblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTblClienteMouseClicked
        // TODO add your handling code here:
        int row = JTblCliente.getSelectedRow();
        String id = model.getValueAt(row, 0).toString();
        String nombre = model.getValueAt(row, 1).toString();
        String email = model.getValueAt(row, 2).toString();
        
        
       
        
        JTxtCliente.setText(id);
        JTxtNombre.setText(nombre);
        JTxtEmail.setText(email);
        JTxtBuscar.setText(id);
        
    }//GEN-LAST:event_JTblClienteMouseClicked

    private void JTxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtBuscarKeyTyped
        // TODO add your handling code here:
        if (evt.getSource().equals(JTxtCliente)) {
            Character c = evt.getKeyChar();
            if (!Character.isDigit(c) && !c.toString().equals("")) {
                evt.consume();
            }
        }
    }//GEN-LAST:event_JTxtBuscarKeyTyped

    private void updateTable() {
        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < model.getRowCount(); j++) {
                model.removeRow(j);
            }
        }
        for (int i = 0; i < clientes.size(); i++) {
            model.addRow(clientes.get(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnBuscar;
    private javax.swing.JButton JBtnEditar;
    private javax.swing.JButton JBtnEliminar;
    private javax.swing.JButton JBtnGuardar;
    private javax.swing.JButton JBtnVolver;
    private javax.swing.JTable JTblCliente;
    private javax.swing.JTextField JTxtBuscar;
    private javax.swing.JTextField JTxtCliente;
    private javax.swing.JTextField JTxtEmail;
    private javax.swing.JTextField JTxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
